Algoritmo "semnome"

Var
 i,a, contador, b: inteiro


Inicio
 a <-0
 contador <- 0
 b <- 0
 
 Escreva ("Digite sua idade: ")
         enquanto (contador<10) faca
         contador <- contador + 1
         leia (i)
              se (i<25) entao
              b <- b + 1
              fimse
         fimenquanto
 Escreva ("O número de pessoas com menos de 25 anos é: ", b)
              
         


Fimalgoritmo