Algoritmo "semnome"

Var

n, soma, contador: inteiro
media: real

Inicio
n <- 1
contador <- 0
soma <- 0
Escreva (" Digite as idades dos alunos: ")
        enquanto (n>0) faca
        leia (n)
             se (n>=0) entao
             soma <- soma + n
             contador <- contador + 1
             media <-  soma/contador
              fimse
        fimenquanto
Escreval (" A media de idades é: ",media)


Fimalgoritmo