Algoritmo "trecho"
// Disciplina   : Linguagem e Lógica de Programação
// Professor   : Cátia Khouri
// Autor(a)    : Edson Araujo de Souza Neto
// Data atual  : 19/07/2022

Var
poeasia: caractere
a: caractere
b: caractere

Inicio
a <- ("canto")
b <- ("sou poeta.")
Escreva ("Eu ", a, " porque o instante existe ")
Escreva ("e a minha vida está completa.")
Escreva (" Não sou alegre nem sou triste ")
Escreva ( b)

Fimalgoritmo